Metrics/ClassLength:
  Max: 150

Metrics/MethodLength:
  Max: 20

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/SingleArgumentDig:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/RaiseArgs:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false
